In [1]:
import pandas as pd
import numpy as np
import json

In [11]:
with open("../config/settings.json", 'r') as f:
    settings = json.load(f)
    
with open("../config/asset_types.json", 'r') as f:
    asset_types = json.load(f)

In [12]:
START_DATE = settings["START_DATE"]
END_DATE = settings["END_DATE"]
INTERVAL_DUR = settings["INTERVAL_DUR"]

In [13]:
date_range = pd.date_range(START_DATE,END_DATE,freq=INTERVAL_DUR)
date_range

DatetimeIndex(['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01',
               '2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01',
               '2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01',
               '2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01', '2025-07-01', '2025-08-01',
               '2025-09-01', '2025-10-01', '2025-11-01', '2025-12-01',
               '2026-01-01'],
              dtype='datetime64[us]', freq='MS')

**Load Data**

In [14]:
df_stocks = pd.read_csv("../data/raw/stocks.csv", delimiter=";")
df_stocks["Date"] = pd.to_datetime(df_stocks["Date"], format="%d/%m/%Y")

In [15]:
df_stocks

,Date,Ticker,ISIN,Full Name,Amount spent,Price / piece,Amount,Total price,Type
0,2022-03-28,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,106.40,106.40,1,106.40,BUY
1,2025-01-27,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,269.60,134.30,2,268.60,BUY
2,2025-02-28,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,135.30,134.30,1,134.30,BUY
3,2025-03-27,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,257.52,128.26,2,256.52,BUY
4,2025-06-25,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,510.04,127.26,4,509.04,BUY
5,2025-09-24,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,411.10,136.70,3,410.10,BUY
6,2025-11-26,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,847.20,140.70,6,844.20,BUY
7,2026-03-23,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,1123.80,140.10,8,1120.80,BUY
8,2026-05-22,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,789.30,157.26,5,786.30,BUY
9,2026-07-23,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,960.84,159.64,6,957.84,BUY

In [16]:
df_stocks[df_stocks["Date"] > date_range[0]]

,Date,Ticker,ISIN,Full Name,Amount spent,Price / piece,Amount,Total price,Type
0,2022-03-28,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,106.40,106.40,1,106.40,BUY
1,2025-01-27,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,269.60,134.30,2,268.60,BUY
2,2025-02-28,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,135.30,134.30,1,134.30,BUY
3,2025-03-27,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,257.52,128.26,2,256.52,BUY
4,2025-06-25,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,510.04,127.26,4,509.04,BUY
5,2025-09-24,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,411.10,136.70,3,410.10,BUY
6,2025-11-26,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,847.20,140.70,6,844.20,BUY
7,2026-03-23,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,1123.80,140.10,8,1120.80,BUY
8,2026-05-22,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,789.30,157.26,5,786.30,BUY
9,2026-07-23,AMS:VWRL,IE00B3RBWM25,Vanguard FTSE All-World UCITS ETF USD Dis,960.84,159.64,6,957.84,BUY

In [17]:
out = df_stocks.resample('MS', on="Date").sum()[["Total price", "Amount"]]
out.cumsum()

            Total price  Amount
Date
2022-03-01       106.40       1
2022-04-01       106.40       1
2022-05-01       106.40       1
2022-06-01       106.40       1
2022-07-01       106.40       1
2022-08-01       106.40       1
2022-09-01       106.40       1
2022-10-01       106.40       1
2022-11-01       106.40       1
2022-12-01       106.40       1
2023-01-01       106.40       1
2023-02-01       106.40       1
2023-03-01       106.40       1
2023-04-01       106.40       1
2023-05-01       106.40       1
2023-06-01       106.40       1
2023-07-01       106.40       1
2023-08-01       106.40       1
2023-09-01       106.40       1
2023-10-01       106.40       1
2023-11-01       106.40       1
2023-12-01       106.40       1
2024-01-01       106.40       1
2024-02-01       106.40       1
2024-03-01       106.40       1
2024-04-01       106.40       1
2024-05-01       106.40       1
2024-06-01       106.40       1
2024-07-01       106.40       1
2024-08-01       106.40       1
2024-09-01       106.40       1
2024-10-01       106.40       1
2024-11-01       106.40       1
2024-12-01       106.40       1
2025-01-01       375.00       3
2025-02-01       509.30       4
2025-03-01       765.82       6
2025-04-01       765.82       6
2025-05-01       765.82       6
2025-06-01      1274.86      10
2025-07-01      1274.86      10
2025-08-01      1274.86      10
2025-09-01      1684.96      13
2025-10-01      1684.96      13
2025-11-01      2529.16      19
2025-12-01      2529.16      19
2026-01-01      2529.16      19
2026-02-01      2529.16      19
2026-03-01      3649.96      27
2026-04-01      3649.96      27
2026-05-01      4436.26      32
2026-06-01      4436.26      32
2026-07-01      5394.10      38

In [18]:
from cashdash.asset_classes import ASN

In [19]:
asn = ASN()

In [ ]:
asn.load_data()